### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by patrigarcia** [igrowker/i002-talentplace-front#1]
1. Crear el componente de landing page para la plataforma con secciones y contenido. Respetar los colores (los encontrarán en la documentación de UX).
NOTA: Para la UI por favor charlen con el equipo de UX que les proporcionarán las pantallas iniciales o las guías de estilo.

2.
- Hero section: Información destacada de la plataforma.
- Features section: Características y beneficios.
- Call to Action: Botones para registro e inicio de sesión.

**Comment by kjnoviello** [comment]
Realizar el display de la Landing en responsive, con rutas completas y ultimar detalles restantes si es que quedan.
