### ISSUE TITLE
Sidebar dashboard empresa

### ISSUE THREAD

**Issue by kjnoviello** [igrowker/i002-talentplace-front#34]
Implementar un Sidebar que permita a las empresas navegar entre las diferentes secciones del dashboard. 
-	Los enlaces deben estar activos (resaltados) cuando la ruta actual corresponda a la sección específica.
-	Las variables de estilo (colores, fuentes, etc.) deben utilizar las definidas en el archivo de estilos global.
-	En caso necesario, reutilizar otros componentes.
-	Asegurar que el diseño sea responsivo en pantallas más pequeñas y que el sidebar quede oculto pudiendo acceder al mismo a través de un botón en la parte superior.
-	Configurar las rutas de los links y conectarlos a las otras páginas creándolas en caso de que no estén creadas (para luego volcar los correspondientes componentes que se van creando)

**Comment by kjnoviello** [comment]
![Image](https://github.com/igrowker/i002-talentplace-front/assets/125762357/63d1817e-4ebe-4aca-a03c-395ef4489033)





![Image](https://github.com/igrowker/i002-talentplace-front/assets/125762357/543219b0-38ea-408b-ab57-977028790433)

**Comment by DEV-AusA** [comment]
Hola Xabi, te comento lo que vi hasta el momento:
Actualizar el repo para trabajar con los componentes integrados de cada seccion.
- En principio el Router debe redirigir al Componente Dashboard, dentro de este componente faltaria implementar la logica para renderizar un componente SidebarEmpresa o SidebarFreelancer esto lo dejo a tu criterio (lo mas recomendable de momento seria verificar el rol del usuario en la data del mismo) y de a cuerdo a su rol renderizar uno o el otro.
- Faltaria colocar el hover y el color en cada seccion donde se encuentre el usuario.
- Renderizar los datos del perfil faltante (email)
- Agregar funcionalidad al boton "Salir" implementarlo con "sweetalert" que es el que tenemos trabajando de momento.

El resto esta excelente!, sigamos asi!
Creo que no me olvido nada mas, cualquier inconveniente me chiflas y lo vemos,
