### ISSUE TITLE
Login y register

### ISSUE THREAD

**Issue by patrigarcia** [igrowker/i002-talentplace-front#7]
1. Crear el componente RegisterForm con un formulario para capturar email, contraseña, nombre y tipo de usuario. 
2. Crear el componente LoginForm con un formulario para iniciar sesión con mail, contraseña.
3. Manejo de errores y mensajes de validación de campos (pueden usar Formik o Yup). Expresiones regulares para validar formatos. Requisitos de seguridad para la contraseña (longitud mínima, caracteres especiales), etc. 
4. Integración con backend.

**Comment by kjnoviello** [comment]
Maquetar y realizar la lógica para la pantalla de “restablecer contraseña” e integrar al back.

**Comment by XabierGallardo** [comment]
Esperando coordinación con equipo backend para hacer la Integración

**Comment by XabierGallardo** [comment]
Último paso completado, integrado login y register con el backend
